import Head from "next/head";

export default function Meta() {
  return (
    <Head>
      <title>Samir Shrestha | Web Developer</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta property="og:title" content="Samir Shrestha | Web Developer"></meta>
      <meta property="og:type" content="Website"></meta>
      <meta property="og:url" content="https://thefakedeal.github.io"></meta>
      <meta
        property="og:image"
        content="https://avatars.githubusercontent.com/thefakedeal"
      ></meta>

      <meta
        property="twitter:title"
        content="Samir Shrestha | Web Developer"
      ></meta>
      <meta
        property="twitter:image"
        content="https://avatars.githubusercontent.com/thefakedeal"
      ></meta>
      <meta property="twitter:card" content="Website"></meta>
    </Head>
  );
}
