import Head from 'next/head'
import Backdrop from '../components/Backdrop'
import DisplayPicture from '../components/DisplayPicture'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} py-4`}>
        <div className="row w-100 px-4">
          <section title='Introduction' className="col-md-8 d-flex align-items-md-center">
            <div>
              <h1 className='text-white'>
              Hello I'm Samir Shrestha. <br />
                I'm A Full Stack Web Developer! 
              </h1>
              <div
                className={styles.links}
              >
                <a href="https://github.com/Thefakedeal" target="_blank">
                  <img src="/img/ghub.png" alt="Github" className={styles.link_img} />
                </a>

                <a href="https://www.linkedin.com/in/samir-shrestha-16050a210/" target="_blank">
                  <img src="/img/linkedin.png" alt="Linkedin" className={styles.link_img} />
                </a>
              </div>
            </div>
          </section>
          <div className="col-md-4 d-flex align-items-center justify-content-center">
            <div className="col-8 py-4 col-md-12">
              <DisplayPicture />
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
